### ISSUE TITLE
Seems to work but no styles!

### ISSUE THREAD

**Issue by Koleok** [D34THWINGS/ng-redux-dev-tools#7]
I am able to get the middleware installed and running, and the hotkey to show it works, but none of the styles are coming along for the ride. This means I can't really use it in my dev workflow without hand-jamming a bunch of dom modifications to even see it, even then it is plain html

**Comment by D34THWINGS** [comment]
My library doesn't make sense anymore because there's now a Chrome Extension that handles all the things for you : https://github.com/zalmoxisus/redux-devtools-extension. Doesn't require React, just a simple ternary expression in your code, so you better check it out !

But if you need to make my tools to work, you need to include in some way the sass styles by including the file `src/index.scss`, I forgot to mention that in the documentation

**Comment by D34THWINGS** [comment]
I can do an update with plain CSS files if you need. I can see a use case of this project over the extension is where you want to have more control of your tooling, because the Chrome Extension can't be modified easily

**Comment by Koleok** [comment]
Actually the chrome extension will be a great resource to get others up and running fast with this, I am looking at the [ternary you mentioned](https://github.com/zalmoxisus/redux-devtools-extension/commit/6c146a2e16da79fefdc0e3e33f188d4ee6667341) in the extension repo but i am wondering what the parallel is since my angular app doesn't configure the store the same. 

That example has something like:

``` javascript
const finalCreateStore = compose(
    applyMiddleware(thunk),
    window.devToolsExtension ? window.devToolsExtension() : f => f
  )(createStore);

  const store = finalCreateStore(reducer, initialState);
```

Seems like the closes thing i have to this is in using `$ngReduxProvider` to `createStoreWith` like:

``` javascript
$ngReduxProvider.createStoreWith(rootReducer, [
    'ngUiRouterMiddleware',
    thunk,
    createLogger(),
  ]);
```

**Comment by Koleok** [comment]
I guess my answer will lie [here in the ng-redux source](https://github.com/wbuchwalter/ng-redux/blob/84fc57c415f1cd8b25128a3c420f9f284e4b2b37/src/components/ngRedux.js), the third argument to `createStoreWith` is enhancers

``` javascript
$ngReduxProvider.createStoreWith(rootReducer, [
    'ngUiRouterMiddleware',
    thunk,
    createLogger(),
  ], [
    window.devToolsExtension ? window.devToolsExtension() : f => f,
]);
```

**Comment by leonardoanalista** [comment]
I configured like previous comment. 

```
export default angular.module('testMod', [
  ...
  ngRedux
]).config(($ngReduxProvider) => {
  $ngReduxProvider.createStoreWith({
    reducer1,reducer2
  }
  , [logger], [window.devToolsExtension ? window.devToolsExtension() : f => f]);
}).run(['ApiManagerService', 'appConfig', function (ApiManangerService, appConfig) {
  ApiManangerService.setAppConfig(appConfig);
}]).name
```

It seems like when you toggle a state, I need to manually kick off a $digest loop. The way I see the result is when I perform an action in the app that kicks the $digest loop off. 
Is that normal? Is there a way to fix that?

**Comment by D34THWINGS** [comment]
That's because the Extension isn't in the same window and therefore angular can't know that you clicked somewhere to trigger a digest loop. I think you'll need to do some extra research on the extension repository :/

**Comment by leonardoanalista** [comment]
That's fine. It is my first time using redux, I am still getting my head around. For Dev, I manually run a digest loop manually when necessary. I also enabled panels so redux-dev-tools behaves just like console or any other panel. 
Thanks for the reply.

**Comment by D34THWINGS** [comment]
You're welcome !
